name: tests

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Up Ruby and Ceedling
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.5

    - name: Install Ceedling
      run: gem install ceedling

    - name: Build and Run Ceedling Tests
      run: |
        ceedling test:all
