/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_plugin_null(void);
extern void test_plugin_null_name(void);
extern void test_plugin_not_boostrapped(void);
extern void test_plugin_init_values_all(void);
extern void test_plugin_exists(void);
extern void test_register_plugin(void);
extern void test_unregister_plugin(void);
extern void test_register_plugin_function_invalid_inputs(void);
extern void test_register_plugin_function_valid_input(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_plugin.c");
  run_test(test_plugin_null, "test_plugin_null", 44);
  run_test(test_plugin_null_name, "test_plugin_null_name", 50);
  run_test(test_plugin_not_boostrapped, "test_plugin_not_boostrapped", 62);
  run_test(test_plugin_init_values_all, "test_plugin_init_values_all", 69);
  run_test(test_plugin_exists, "test_plugin_exists", 77);
  run_test(test_register_plugin, "test_register_plugin", 83);
  run_test(test_unregister_plugin, "test_unregister_plugin", 88);
  run_test(test_register_plugin_function_invalid_inputs, "test_register_plugin_function_invalid_inputs", 101);
  run_test(test_register_plugin_function_valid_input, "test_register_plugin_function_valid_input", 109);

  return UnityEnd();
}
