name: Run Ceedling Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.5' 
        bundler-cache: true 

    - name: Ceedling run tests
      run: |
        gem install ceedling
        cd test
        ceedling test:all
    
    # - name: List workspace contents
    #   run: |
    #     ls -R $GITHUB_WORKSPACE
    #     find $GITHUB_WORKSPACE -type f
      
    # - name: Echo Current Working Directory
    #   run: |
    #     echo "Current Working Directory: $(pwd)"

    # - name: Clean Ceedling
    #   working-directory: ./test/
    #   run: |
    #     echo "Current Working Directory: $(pwd)"

    # # - name: Clobber Ceedling
    # #   working-directory: ./test/
    # #   run: ceedling clobber

    # - name: Run Ceedling tests
    #   working-directory: ./test/
    #   run: ceedling


