name: Run Ceedling Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.5' 
        bundler-cache: true 

    - name: Install Ceedling
      run: gem install ceedling

    - name: Clean Ceedling
      run: ceedling clean

    - name: Clobber Ceedling
      run: ceedling clobber

    - name: Echo Current Working Directory
      run: |
        echo "Current Working Directory: $(pwd)"
        ceedling test:all
