name: Run Ceedling Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.5' 
        bundler-cache: true 

    - name: Install Ceedling
      run: gem install ceedling
    
    - name: List workspace contents
      run: |
        ls -R $GITHUB_WORKSPACE
        find $GITHUB_WORKSPACE -type f
      
    - name: Echo Current Working Directory
      run: |
        echo "Current Working Directory: $(pwd)"

    - name: Clean Ceedling
      working-directory: ../test/
      run: ceedling clean

    - name: Clobber Ceedling
      run: ceedling clobber


