name: main

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Up Ruby and Ceedling
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.5

    - name: Install Ceedling
      run: gem install ceedling

    - name: Run Ceedling Clean
      working-directory:  ../
      run:  ceedling clean

    - name: Run Ceedling Clobber
      run : |
        echo "Current Working Directory: $(pwd)"
        ceedling clobber
        
    - name: Run Ceedling tests
      run : |
        ceedling test
    
