name: Produce valgrind memory reports
on: [push, pull_request]

jobs:

  valgrind:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.5'

    - name: Install Ceedling
      run: gem install ceedling


    - name: Set LD_LIBRARY_PATH
      run: |
        echo "LD_LIBRARY_PATH=./reqs/lib/" >> $GITHUB_ENV

    - name: Test
      run: |
        ceedling clean
        ceedling clobber
        ceedling verbosity[1] test:all

    - name: Set up Valgrind
      run: |
        sudo apt-get update -q
        sudo apt-get install -y valgrind

    - name: Run Valgrind Tests
      run: |
        cd test_valgrind/
        rm valgrind_output/ -rf
        ./run_scripts.sh

    - name: Upload Valgrind Reports
      uses: actions/upload-artifact@v3
      with:
        path: ./valgrind_output/
